<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_admindemo.com</name>
   <tag></tag>
   <elementGuidId>e43fedc6-203a-4011-bac8-18630a8237b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.box-content.demo-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>48ed2e6a-4b5b-4201-a414-8f3ff5f05f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-content demo-email</value>
      <webElementGuid>30b7543b-e1e5-4b72-978f-e62a4f23cad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>admin@demo.com</value>
      <webElementGuid>a5155c3a-c321-4a53-83a0-6d5857f50edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;form-signin&quot;]/div[@class=&quot;card bg-white mb15&quot;]/div[@class=&quot;card-body p30 rounded-bottom&quot;]/div[@class=&quot;box p10 clickable fill-login b-b&quot;]/div[@class=&quot;box-content demo-email&quot;]</value>
      <webElementGuid>0be9c68a-0a6e-4164-a633-b079e49737c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::div[1]</value>
      <webElementGuid>05885205-ad14-4b16-a474-8d166ff2e345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in as'])[1]/following::div[3]</value>
      <webElementGuid>ff0245a3-0f3d-4144-8d7b-03a247019e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='riseDemo'])[1]/preceding::div[1]</value>
      <webElementGuid>f41b5710-f05a-4208-b53d-e6c2e887777e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client'])[1]/preceding::div[2]</value>
      <webElementGuid>ec5cd354-e1c2-4a45-97ba-0ca983e56b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='admin@demo.com']/parent::*</value>
      <webElementGuid>c66116d2-87db-468f-bb75-bbd75e307103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]</value>
      <webElementGuid>6961b72e-a793-4ae8-b260-99decead3bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'admin@demo.com' or . = 'admin@demo.com')]</value>
      <webElementGuid>04afb34d-9c04-4495-afaa-7d067546ec89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
