<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_first_name</name>
   <tag></tag>
   <elementGuidId>c7baa76a-7cd1-464e-9433-f3685084c2eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#first_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='first_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0dee0992-fc8f-4c8d-93fd-ed9d5c517ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d216b8d-0572-4d87-8ac1-f9d2b0b2ecc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>first_name</value>
      <webElementGuid>99f4a872-3ed9-496b-b129-4232292d00a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>first_name</value>
      <webElementGuid>b654b9c4-2f18-41a0-9151-395780d3b547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fdbfe9e5-95ac-4313-bdc1-dcf720f303ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>add058f9-d9cf-431a-a29e-302e1cd9a206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rule-required</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e460fd50-8433-444a-b241-e8375a9d4bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-required</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>6908cb36-81e2-4556-9d17-84b2c01fa551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;first_name&quot;)</value>
      <webElementGuid>3d403a5e-4f8e-4e75-b677-1da621f62510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='first_name']</value>
      <webElementGuid>77396fec-463f-41e9-be1c-fd1b4b82fb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup-form']/div/div/input</value>
      <webElementGuid>9d4abc58-f809-4e1b-a4bb-4e3f40e20edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>81071eb7-e92a-47d5-9e6a-9e1240d4093e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'first_name' and @id = 'first_name']</value>
      <webElementGuid>841527e8-3ac0-4328-9645-dc356070ede3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
