<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Organization_account_type</name>
   <tag></tag>
   <elementGuidId>01f46b87-364b-4eb7-987e-3917f1a0670d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#type_person</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='type_person']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b876757a-45d6-40f8-b105-d02846caeb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>efdf9501-e1fa-4f0b-8d88-88e7daf394e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account_type</value>
      <webElementGuid>5e680716-ff83-438b-8d69-287d1b280636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>person</value>
      <webElementGuid>908974ad-9250-4e65-aba5-d9a2a38f0831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>type_person</value>
      <webElementGuid>b591a951-9b2b-481c-8e87-f8e2e75dce81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input account-type</value>
      <webElementGuid>0500ba45-0d9f-4c7a-abe6-056050d5de36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-required</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>85134b7e-4bc2-4228-a76b-a3c943ed5ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;type_person&quot;)</value>
      <webElementGuid>289422c0-f2ba-46fe-bc27-9ee51fe4ab69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='type_person']</value>
      <webElementGuid>22feae18-0b89-4a6a-ad9f-06498cf9922e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup-form']/div[3]/div/div/input[2]</value>
      <webElementGuid>f8c330f3-fc0d-417d-8dec-61e8321d65ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>d122e3d7-9a12-4f9a-8178-ff48cf8fbae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'account_type' and @id = 'type_person']</value>
      <webElementGuid>f27acd13-ecf9-4ffd-aadd-de7e211960fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
