<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Retype password_retype_password</name>
   <tag></tag>
   <elementGuidId>2ee002a5-55de-4bf2-b1d7-05598e07210d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#retype_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='retype_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f8dc202-86e6-429d-88a3-fca1872e3679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ce1f6f99-f1c3-4e62-a368-b909a23ef2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>retype_password</value>
      <webElementGuid>d3a13461-4f50-4651-b1f7-baacfe853ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>retype_password</value>
      <webElementGuid>2b9ed507-ae52-4e77-ba1a-c99dfe78a8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>07868c36-a4ba-43cf-9f53-f2b8ed98e5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8d3dd9b5-8e92-4d7c-824b-8a23275795a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rule-equalto</name>
      <type>Main</type>
      <value>#password</value>
      <webElementGuid>d3616776-f2d6-4e8f-b2ee-744050a753dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-equalto</name>
      <type>Main</type>
      <value>Please enter the same value again.</value>
      <webElementGuid>35ca8017-1495-4bdf-bf79-cb4ebdd45ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retype_password&quot;)</value>
      <webElementGuid>6cdaa52d-53cd-4467-9e8a-48960f934f08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='retype_password']</value>
      <webElementGuid>b5056a33-aef4-45a5-bd2c-890e9ddf732a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup-form']/div[7]/div/input</value>
      <webElementGuid>79c6189e-7d23-4cc7-86f3-504c97b45faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>c2a508d7-5127-49d8-b39a-6eb92b00f44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'retype_password' and @id = 'retype_password']</value>
      <webElementGuid>1f73f3a1-19b7-483c-af98-c20cae27f6f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
