<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type_account_type</name>
   <tag></tag>
   <elementGuidId>583a447d-7a17-481f-a91f-e520ba6c8ce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#type_organization</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='type_organization']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abc7b34e-b08d-4bbd-a793-9c8fe1edd5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>453ae2c4-7e27-4abe-9d61-0440bebaab00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account_type</value>
      <webElementGuid>a0450cd6-f087-4fcd-a4ab-0530997f8cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>0689883d-635f-4eb7-9108-78cb2b173afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>6606c2b1-ef21-4b6c-819e-765cde8551ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>type_organization</value>
      <webElementGuid>5dd53bf7-3a8b-4633-8bf8-75c4070a158d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input account-type</value>
      <webElementGuid>b0b25065-9f12-4373-bea8-cc48468d67f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-required</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>ed6a4ff1-f488-417e-951f-f34bcdaa920c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;type_organization&quot;)</value>
      <webElementGuid>187c1052-a4a4-417d-aa1c-03b100ff09f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='type_organization']</value>
      <webElementGuid>05b9508f-cca0-4712-995b-e40873a9654a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup-form']/div[3]/div/div/input</value>
      <webElementGuid>c39c9f03-30b5-4c46-bf33-5cc58c298bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>f45542af-5fb3-4349-a2f7-4f1a2d0abff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'account_type' and @checked = 'checked' and @id = 'type_organization']</value>
      <webElementGuid>f0cdfc62-837f-4877-98ee-269d1d58e890</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
